#!/usr/bin/env python3
"""
Migration utility for converting Model Cards to use Datasheets references.

This script helps migrate from simple dataSet references to external Datasheets
for Datasets references (Pattern 1 integration).

Usage:
    python utils/migrate_to_harmonized.py input.yaml output.yaml

Features:
    - Converts simple dataSet entries to datasheet references
    - Generates stub datasheet files for each dataset
    - Updates model_language (from language)
    - Preserves all other model card content
    - Creates backward-compatible output
"""

import sys
import yaml
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime


def load_yaml(file_path: str) -> Dict[str, Any]:
    """Load YAML file."""
    with open(file_path, 'r') as f:
        return yaml.safe_load(f)


def save_yaml(data: Dict[str, Any], file_path: str):
    """Save YAML file with nice formatting."""
    with open(file_path, 'w') as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


def generate_dataset_id(dataset_name: str) -> str:
    """Generate a dataset ID from name."""
    # Convert to lowercase, replace spaces/special chars with hyphens
    return dataset_name.lower().replace(' ', '-').replace('_', '-') + '-v1'


def create_datasheet_stub(dataset: Dict[str, Any], output_dir: Path) -> Dict[str, Any]:
    """
    Create a stub datasheet file for a dataset.

    Returns metadata about the created datasheet.
    """
    dataset_name = dataset.get('name', 'Unknown Dataset')
    dataset_id = generate_dataset_id(dataset_name)

    # Create comprehensive datasheet stub
    datasheet = {
        'id': dataset_id,
        'name': dataset_name,
        'description': dataset.get('description', f'Documentation for {dataset_name}'),
        'download_url': dataset.get('link', 'https://example.org/dataset'),
        'version': '1.0',
        'created_on': datetime.now().strftime('%Y-%m-%d'),

        # Motivation section
        'motivation': {
            'purposes': [
                {'description': 'TODO: Document why this dataset was created'}
            ],
            'tasks': [
                {'description': 'TODO: Document the tasks this dataset supports'}
            ],
            'creators': [
                {
                    'principal_investigator': {
                        'name': 'TODO: Add creator name',
                        'email': 'TODO: Add creator email',
                        'affiliation': {
                            'name': 'TODO: Add organization'
                        }
                    }
                }
            ]
        },

        # Composition section
        'composition': {
            'instances': [
                {
                    'description': 'TODO: Describe the instances in this dataset',
                    'instance_count': 0,  # TODO: Add actual count
                    'instance_type': 'TODO: Describe instance type'
                }
            ],
            'sensitive_elements': []
        },

        # Collection section
        'collection': {
            'acquisition_methods': [
                {'description': 'TODO: How was data acquired?'}
            ],
            'collection_mechanisms': [
                {'description': 'TODO: What mechanisms were used?'}
            ]
        },

        # Ethics section
        'ethics': {
            'ethical_reviews': [
                {'description': 'TODO: Document ethical review process'}
            ]
        },

        # Preprocessing section
        'preprocessing': {
            'preprocessing_strategies': [
                {'description': 'TODO: Document preprocessing steps'}
            ]
        },

        # Uses section
        'uses': {
            'existing_uses': [
                {'description': 'TODO: Document known uses'}
            ],
            'discouraged_uses': [
                {'description': 'TODO: Document discouraged uses'}
            ]
        },

        # Distribution section
        'distribution': {
            'license_and_use_terms': [
                {'description': 'TODO: Document licensing terms'}
            ]
        },

        # Maintenance section
        'maintenance': {
            'maintainers': [
                {
                    'maintainer': {
                        'name': 'TODO: Add maintainer name',
                        'email': 'TODO: Add maintainer email'
                    }
                }
            ]
        },

        # Variables section
        'variables': [],  # TODO: Add variable descriptions

        'notes': f"""
        This is a STUB datasheet generated by the migration utility.

        TODO: Complete all sections marked with TODO.

        For comprehensive dataset documentation, fill in:
        - Motivation (why created, funding, creators)
        - Composition (instances, subsets, sensitive data)
        - Collection (methods, sampling, timeframes)
        - Ethics (reviews, consent, privacy)
        - Preprocessing (cleaning, labeling)
        - Uses (existing, discouraged, impacts)
        - Distribution (formats, licensing)
        - Maintenance (update plans, version access)
        - Variables (field descriptions)

        See examples in src/data/examples/harmonized/ for complete datasheets.
        Reference: https://github.com/bridge2ai/data-sheets-schema
        """
    }

    # Save datasheet
    datasheet_file = output_dir / f"{dataset_id}.yaml"
    save_yaml(datasheet, str(datasheet_file))

    print(f"  Created stub datasheet: {datasheet_file}")
    print(f"  ⚠️  TODO: Edit {datasheet_file} to complete dataset documentation")

    return {
        'id': dataset_id,
        'name': dataset_name,
        'datasheet_url': f'https://datasheets.example.org/{dataset_id}.yaml',  # TODO: Update URL
        'datasheet_format': 'datasheets-for-datasets-v1.0',
        'description': f'Complete dataset documentation following Datasheets for Datasets framework'
    }


def migrate_model_card(input_data: Dict[str, Any], datasheet_output_dir: Path) -> Dict[str, Any]:
    """
    Migrate a model card to use datasheet references.

    Returns the migrated model card data.
    """
    output_data = input_data.copy()

    # 1. Handle language → model_language migration
    if 'language' in output_data:
        output_data['model_language'] = output_data.pop('language')
        print("✓ Migrated 'language' → 'model_language'")

    # 2. Handle model_parameters.data → dataset references
    if 'model_parameters' in output_data:
        params = output_data['model_parameters']

        if 'data' in params:
            datasets = params['data']
            if not isinstance(datasets, list):
                datasets = [datasets]

            # Create datasheet stubs
            datasheet_refs = []
            for dataset in datasets:
                if isinstance(dataset, dict):
                    datasheet_ref = create_datasheet_stub(dataset, datasheet_output_dir)
                    datasheet_refs.append(datasheet_ref)

            # Add dataset_documentation section
            if 'dataset_documentation' not in output_data:
                output_data['dataset_documentation'] = {}

            output_data['dataset_documentation']['training_datasets'] = datasheet_refs

            # Keep original data for backward compatibility
            # Add note about datasheet reference
            for dataset in datasets:
                if isinstance(dataset, dict):
                    dataset['datasheet_info'] = (
                        "Complete dataset documentation available as separate Datasheet. "
                        "See dataset_documentation section for references."
                    )

            print(f"✓ Created {len(datasheet_refs)} datasheet reference(s)")

    # 3. Add migration metadata
    if 'migration_info' not in output_data:
        output_data['migration_info'] = {
            'migrated_on': datetime.now().isoformat(),
            'migration_tool': 'migrate_to_harmonized.py v1.0',
            'migration_pattern': 'Pattern 1: External References',
            'notes': (
                'This model card has been migrated to reference external Datasheets for Datasets. '
                'Complete the stub datasheet files in the datasheets/ directory.'
            )
        }

    return output_data


def main():
    """Main migration function."""
    if len(sys.argv) < 3:
        print("Usage: python utils/migrate_to_harmonized.py input.yaml output.yaml")
        print()
        print("This tool migrates model cards to use Datasheets for Datasets references.")
        print("It will:")
        print("  1. Convert 'language' → 'model_language'")
        print("  2. Create stub datasheet files for each dataset")
        print("  3. Add dataset_documentation section with datasheet references")
        print("  4. Preserve backward compatibility")
        print()
        print("Output:")
        print("  - Migrated model card: output.yaml")
        print("  - Stub datasheets: datasheets/*.yaml (needs completion)")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    print(f"Model Card Migration Tool")
    print(f"=" * 60)
    print(f"Input:  {input_file}")
    print(f"Output: {output_file}")
    print()

    # Create datasheets directory
    datasheet_dir = Path('datasheets')
    datasheet_dir.mkdir(exist_ok=True)

    # Load input
    print("Loading input model card...")
    try:
        input_data = load_yaml(input_file)
    except Exception as e:
        print(f"❌ Error loading input file: {e}")
        sys.exit(1)

    # Migrate
    print("\nMigrating model card...")
    try:
        output_data = migrate_model_card(input_data, datasheet_dir)
    except Exception as e:
        print(f"❌ Error during migration: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

    # Save output
    print(f"\nSaving migrated model card to {output_file}...")
    try:
        save_yaml(output_data, output_file)
    except Exception as e:
        print(f"❌ Error saving output file: {e}")
        sys.exit(1)

    print("\n" + "=" * 60)
    print("✅ Migration completed successfully!")
    print()
    print("Next steps:")
    print("  1. Review the migrated model card:", output_file)
    print("  2. Complete the stub datasheet files in datasheets/")
    print("  3. Update datasheet URLs in dataset_documentation section")
    print("  4. Validate the migrated model card")
    print()
    print("See INTEGRATION_GUIDE.md for more information.")


if __name__ == '__main__':
    main()
